### ISSUE TITLE
Feedback: Tidyverse (Afternoon Session)

### ISSUE THREAD

**Issue by nehamoopen** [UtrechtUniversity/workshop-introduction-to-R-and-data#31]
Please leave your feedback for the `tidyverse` component (afternoon session) in this issue, thaaaanks!

**Comment by StefanoRapisarda** [comment]
These were comments made after following the very first course in R, comments are organised by session (corresponding to videos):

- Intro to Tidyverse
    - I think it would be useful spending few words on what is a “package”. According to the level of the workshop I am sure most of the people ignore the programming meaning of the word. Also, explain well the difference between installing, loading, and using. It could be done metaphorically: I buy tools to do a carpentry job, but I do not bring them with me around the house ALL the time (that would make me waste energy), but only when I am ready to work on my project. When needed, then I select what I need from my belt or bag and I use. I will put on my belt (loading) only those tools I need to that specific job, even if I bought (installed) many more;
    
- Import Data
    - I think that before starting loading the data frame, a full overview of what they are going to do is necessary (ex. “We are now going to use what we learned in the previous section to load a database, making custom selections according to our needs, running some very basic statistics on selected columns and row, and, finally, visualise our data. In order to do that, we will also use functions that they are not native of R, but that belong to the Tidyverse package”). Sometimes this is done by the speaker in person, sometimes it is not, so why not adding it to the recorded material?

**Comment by DorienHuijser** [comment]
Hello! I haven't gone through the afternoon session materials (and will not manage before the end of this month). I had only noticed so far that the slides link to `uu.nl/rdm`, that should be `https://uu.nl/rdm`, because otherwise the link does not work. Sorry, not super useful feedback ;)

**Comment by nehamoopen** [comment]
Notes from @Mish-JPFD: 

- In the `penguins` dataset (raw) - there are column names with whitespaces, these should be renamed with underscores.
  - If we change the tsv file, we will need to change the code in the subsequent code chunks...
- Exercise 7: typo, we should use the code we wrote in exercises 5 & 6 - not 4 & 5
- Do we need to rethink the ggplot exercises? Because right now, they don't necessarily 'teach' the basics of ggplot - they pretty much just run the code.

**Comment by DorienHuijser** [comment]
During session notes:

- [ ] Reading in the data from the Rmd chunk requires different code compared to importing manually (the file path in the Rmd should be `../data/penguins_raw.tsv`, when run from the entire environment it should be `data/penguins_raw.tsv`. I think this is a something that we can set in the Rmd or in the settings chunk or something

**Comment by nehamoopen** [comment]
Exercise 9 combines two functions: rename and pivot_wider, I would perhaps just split them...maybe do the renaming earlier in the script as well

**Comment by nehamoopen** [comment]
- [ ] Importing data could be done with a simple `read_tsv` and `read_excel`, instead of having to go through the import menu -> copying the code -> having to figure out the concept of delimiters + how to specify them in arguments with (for example) `/t` -> reformatting the date...

- [ ] After a cleaner section on  _importing data_, you could have a section on some basic cleaning/tidying operations which includes formatting dates (currently combined with importing data) and renaming columns (currently combined with pivoting data). 

- [ ] After the above two sections are done with simple, clean functions - we can introduce the participants to piping and have them chain all the three together (import, rename, reformat). Then moving onto the rest of the exercises will be easier...
