### ISSUE TITLE
Points to improve after workshop 20190215

### ISSUE THREAD

**Issue by J535D165** [UtrechtUniversity/workshop-introduction-to-R-and-data#9]
- [x] don't overwrite fc on slide Vectors and Factors
- [x] use as.factor instead of factor
- [x] generate data.frame with age and names directly. (To fix issue with age)
- [x] selecting from data frame more elaborate explanation, including column name as index!

**Comment by J535D165** [comment]
The difference between None, NULL and NA. 

It's like determining whether there is coffee or tea in cup. None, there is nothing in the cup. NA we didn't know what's in there. NULL, there isn't even a cup (we can't put something in there at all).

**Comment by bvreede** [comment]
- [ ] get people to remove the source vectors for their data frame before the exercise, using `rm()`
- [ ] there are more ways to get to the resulting names, eg `df$name[df$age<30]`

**Comment by J535D165** [comment]
Afternoon:

- [ ] tidyverse doesn't load when executing rmarkdown as a cell. Only when you execute the line of code.

**Comment by bvreede** [comment]
- [ ] Check the calculation of mag_magnetic. I think there's a double magnetic_y in there.

**Comment by bvreede** [comment]
> Afternoon:
> 
> * [ ]  tidyverse doesn't load when executing rmarkdown as a cell. Only when you execute the line of code.

Bet you that it's fine.

**Comment by bvreede** [comment]
> The difference between None, NULL and NA.
> 
> It's like determining whether there is coffee or tea in cup. None, there is nothing in the cup. NA we didn't know what's in there. NULL, there isn't even a cup (we can't put something in there at all).

Cool idea! But also perhaps a bit confusing, esp since we're using `NULL` to initialize a variable later on... where is the cup then?

**Comment by bvreede** [comment]
> > The difference between None, NULL and NA.
> > It's like determining whether there is coffee or tea in cup. None, there is nothing in the cup. NA we didn't know what's in there. NULL, there isn't even a cup (we can't put something in there at all).
> 
> Cool idea! But also perhaps a bit confusing, esp since we're using `NULL` to initialize a variable later on... where is the cup then?

Can we say that we have specified the concept of a cup? But not generated one yet.

**Comment by J535D165** [comment]
> Cool idea! But also perhaps a bit confusing, esp since we're using `NULL` to initialize a variable later on... where is the cup then?

Good point. Let me rethink this.

**Comment by bvreede** [comment]
> * [ ]  In-slide explainer of Rstudio interface! Not just a demo. Use the cheat sheet for this?

I checked the cheat sheet --- it's super useful, but not for a first meeting of rstudio. I'll make a slide instead.
